#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd & disown
picom --backend xrender & disown
$HOME/.config/polybar/launch.sh & disown

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          5

#bspc config focus_follows_pointer true


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#reglas de lanzamiento para algunas apps

bspc rule -a "pwvucontrol" state=floating rectangle=900x500+0+48
feh --bg-fill $HOME/Imágenes/lofi/wallpaper.jpg & disown
nm-applet & disown
